#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=90

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc

	mkdir -p /var/lock
	chmod 1777 /var/lock
	mkdir -p /var/log
	mkdir -p /var/run
	ln -s /var/run /run
	ln -s /var/lock /run/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	mkdir -p /tmp/resolv.conf.d
	touch /tmp/resolv.conf.d/resolv.conf.auto
	ln -sf /tmp/resolv.conf.d/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime -t debugfs debugfs /sys/kernel/debug
	grep -q bpf /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime,mode=0700 -t bpf bpffs /sys/fs/bpf
	grep -q pstore /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime -t pstore pstore /sys/fs/pstore
	mkdir -p /tagparam
	grep -q jffs2 /proc/filesystems && /bin/mount -t jffs2 /dev/mtdblock4 /tagparam
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	touch /tmp/.config_pending
	/sbin/kmodloader

	# eth
	/bin/echo 0 > /proc/sys/net/core/message_cost
	/sbin/if_addr
	/sbin/ifconfig sw hw ether $(cat /tagparam/0_mac_addr)
	/sbin/ifconfig sw up
	/sbin/ifconfig idm1 hw ether $(cat /tagparam/1_mac_addr)
	/sbin/ifconfig idm1 up
	/sbin/ifconfig idm0 hw ether $(cat /tagparam/2_mac_addr)
	/sbin/ifconfig idm0 up
	/sbin/eth_setup
	/sbin/ifconfig eth0 hw ether $(cat /tagparam/3_mac_addr)
	/sbin/ifconfig eth1 hw ether $(cat /tagparam/4_mac_addr)
	/sbin/ifconfig eth2 hw ether $(cat /tagparam/5_mac_addr)
	/sbin/ifconfig eth3 hw ether $(cat /tagparam/6_mac_addr)
	/bin/echo 3 > /sys/devices/virtual/net/eth0/queues/rx-0/rps_cpus
	/bin/echo 3 > /sys/devices/virtual/net/eth1/queues/rx-0/rps_cpus
	/bin/echo 3 > /sys/devices/virtual/net/eth2/queues/rx-0/rps_cpus
	/bin/echo 3 > /sys/devices/virtual/net/eth3/queues/rx-0/rps_cpus
	/bin/echo 1024 > /sys/devices/virtual/net/eth0/queues/rx-0/rps_flow_cnt
	/bin/echo 1024 > /sys/devices/virtual/net/eth1/queues/rx-0/rps_flow_cnt
	/bin/echo 1024 > /sys/devices/virtual/net/eth2/queues/rx-0/rps_flow_cnt
	/bin/echo 1024 > /sys/devices/virtual/net/eth3/queues/rx-0/rps_flow_cnt

	/bin/echo enable=0 > /proc/pon/switch_debug/sw_set_trap_to_cpu_queues_rate_limit

	[ ! -f /etc/config/wireless ] && {
		# compat for bcm47xx and mvebu
		sleep 1
	}

	mkdir -p /tmp/.uci
	[ -f /etc/uci-defaults/30_uboot-envtools ] && (. /etc/uci-defaults/30_uboot-envtools)
	/bin/config_generate
	rm -f /tmp/.config_pending
	/sbin/wifi config
	uci_apply_defaults
	sync
	
	# temporary hack until configd exists
	/sbin/reload_config
}
