name: Automatic Packaging

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        # sudo apt-get update
        sudo apt-get install -y mtd-utils

    - name: Packaging
      run: |
        ./scripts/pack_to_jffs2.sh
        zip -j firmware.zip binary/* tools/* rootfs.jffs2
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: ./firmware.zip

    - name: Check if the event is a tag push
      id: check_tag_push
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "Is tag push"
          echo "IS_TAG_PUSH=true" >> $GITHUB_OUTPUT
        else
          echo "IS_TAG_PUSH=false" >> $GITHUB_OUTPUT
        fi


    - name: Upload Release Asset
      if: steps.check_tag_push.outputs.IS_TAG_PUSH == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: firmware.zip
        asset_name: firmware_${{ github.ref_name }}.zip
        asset_content_type: application/zip
